podcasts:
    - title: The Requiem Podcast
      url: http://therequiem.libsyn.com/rss
      
mixcloudusers:
    - title: DJ Dark Machine
      username: djdarkmachine
      
mixcloudtags:
  - futurepop

station:
  username: "your@email.address"
  password: yourPassword
  id: 12345
  playlist: Mixes
