podcasts:
    - title: Dark Horizons Radio
      url: http://www.darkhorizonsradio.com/podcasts/shows/Dark_Horizons.xml
    - title: Communion After Dark
      url: http://communionafterdark.com/rss.xml
      
mixcloudusers:
    - title: DJ Dark Machine
      username: djdarkmachine
      
mixcloudtags:
  - futurepop

station:
  username: "your@email.address"
  password: yourPassword
  id: 12345
  playlist: Mixes
